# -*- coding: utf-8 -*-
"""easyocr_ocr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CNkXeHRBwdDRTvcGMp2xte8J0ZAvDi1x
"""
def ocr(image):
    import easyocr
    from PIL import ImageDraw,Image
    reader = easyocr.Reader(['en'],gpu = False)



    im = Image.fromarray(image)
    im

    bounds = reader.readtext(im)
    bounds

    def draw_boxes(image, bounds, color = 'yellow',width = 2):
        draw = ImageDraw.Draw(image)
        for bound in bounds:
            p0,p1,p2,p3 = bound[0]
            draw.line([*p0,*p1,*p2,*p3,*p0],fill = color,width = width)
        return image
    draw_boxes(im,bounds)

    len(bounds)

    for i in bounds:
        print(i[1])

import cv2
ocr(cv2.imread(r'E:\Projects\Image Detection\out_file.png'))
