# -*- coding: utf-8 -*-
"""Copy of keras-ocr-notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CdYAw1ghLbFQlz2-5rZ6iIdzm3vqA0Gg

# Installation
"""

"""# Imports"""

import keras_ocr
import matplotlib.pyplot as plt

"""# Download Weights"""

pipeline = keras_ocr.pipeline.Pipeline()

"""# Get Images"""


def keras_oc(images):
  

  len(images)

  plt.figure(figsize = (10,20))
  plt.imshow(images[0])

  plt.figure(figsize = (10,20))
  plt.imshow(images[1])

  """# Get Predictions"""

  prediction_groups = pipeline.recognize(images)

  fig, axs = plt.subplots(nrows=len(images), figsize=(10, 20))
  for ax, image, predictions in zip(axs, images, prediction_groups):
      keras_ocr.tools.drawAnnotations(image=image, 
                                      predictions=predictions, 
                                      ax=ax)

  for i in prediction_groups:
    for ele in i:
      print(ele[0],end= " ")
    print('\n')

  print(prediction_groups)